### ISSUE TITLE
Wood production can never be dropped

### ISSUE THREAD

**Issue by Houkime** [Factorio-Xander-Mod/Xander-Mod#19]
Green science is used throughout the game.
Green science uses Standard Inserters and only them. (No alternative recipe)
Standard inserter uses simple electromechanical circuit.  (No alternative recipe)
Simple electromechanical circuit uses basic wiring board. (No alternative recipe)
Basic wiring board uses wood and wood resins (No alternative recipe).
-> you can never drop wood and wood resins production.

It is  
a) non-efficient since the only way to get stable wood is with Logging Camps. They are slow and there is _no_ electric version of them.
b) unrealistical since... well, you don't really use wooden boards in industry-grade manipulators as long as you can do it the other way.

Solution -> have an alternative recipe for basic wiring board or for simple electromechanical circuit.
This is already a thing with simple coils.

**Comment by mspielberg** [comment]
A known issue; will be fixed once #7 is merged. Circuit Substrates 2 enables a recipe for Simple Electromechanical Circuit using Metallized Fiberglass-Phenolic Board, so Basic Wiring Boards (and wood) become obsolete.

**Comment by Repofme1** [comment]
XM version 1.4.0 enables the recipe to make circuit 1 (electromechanical) from etched board 2, which should fix this problem.
