### ISSUE TITLE
Iron Gear Blank - too much remelting

### ISSUE THREAD

**Issue by Houkime** [Factorio-Xander-Mod/Xander-Mod#23]
In earlier versions of XM this made sense since
a) Furnaces were NOT workstations with selectable recipe
AND
b) Automated mechanical operations are not accessible from start.

Thus you actually ned this long remelting route just to tell your furnaces that you want Iron Gear Blank and not sth else.

However, because in the newer XM you can select a recipe for furnace, extra remelting stages become redundant (why should you need to melt sth into one shape and only then into another? Makes no sense).

Thus it is possible to remake routes into either:

a)

ore->plate->Iron Gear Blank
ore->plate->Iron Forging
ore->plate

b)

ore->Iron Gear Blank
ore->Iron Forging
ore->plate

**Comment by jodokus31** [comment]
I understood, that the reason for multiple remelts was the durability and purity.
Repofme1 wrote in an older post in forum: 
https://forums.factorio.com/viewtopic.php?f=97&t=51868&p=303465#p303465
"However I like the steps iron plate -> cast iron -> iron gear blank, because there is a chemical change you need for making cast iron, so iron gears from plates would not make much sense."

**Comment by Repofme1** [comment]
There is a chemical change going on, like jodokus31 pointed out, so it doesn't make sense to make cast iron gears from plain iron plates.  That being said, seeing it now, it also doesn't make sense to make cast iron from iron plate - that's kind of like removing the carbon and then putting it back.  The particulars can get a lot more complicated than that, but I feel that this change would make things simpler while retaining the chemical aspects I like: cast iron now comes directly from smelting ore.

Resulting setup:
ore -> wrought iron plate
ore -> iron casting -> cast iron gear blank

Now done in commit [https://github.com/Factorio-Xander-Mod/Xander-Mod/commit/416ea317740ba6238c108c3ee3caa27a18f21efa](url)

**Comment by Repofme1** [comment]
Link format test

[416ea31](https://github.com/Factorio-Xander-Mod/Xander-Mod/commit/416ea317740ba6238c108c3ee3caa27a18f21efa)
