### ISSUE TITLE
[1.4.1|16.12 BUG] Uninteractable, unselectable, non-working Burner Labs

### ISSUE THREAD

**Issue by Houkime** [Factorio-Xander-Mod/Xander-Mod#24]
As title says. 
Not only player can't select or interact with Labs, but inserters also.
Also you can place another Lab right on top of the old one (with some unexplained offset).
They are not graphics-only, though - there're still fuel checks going on apparently.

Picture:
![xmglitch](https://user-images.githubusercontent.com/32805122/34483184-b7fe7398-efb4-11e7-8ae3-0b0129f22053.png)

Steps to reproduce:
Any new sandbox/game. 

Edit: Seems like Git version doesn't have this bug in contrast to modportal.

**Comment by Houkime** [comment]
The workaround with collision and selection boxes that was apparently used to address this problem in https://github.com/Factorio-Xander-Mod/Xander-Mod/commit/05bff74c57d850aeea41383092e45b9feec9787f (BTW you should have made it a separate commit because this part is not about tiles) Is not fully sufficient.

Blueprinting remains a problem:

![image](https://user-images.githubusercontent.com/32805122/34485208-3bdf6544-efc1-11e7-97b7-efc1d32785ca.png)
![image](https://user-images.githubusercontent.com/32805122/34485223-4a075424-efc1-11e7-83de-79d7e15dcda2.png)

**Comment by ko5h** [comment]
same problem 
![factorio_2018-01-03_21-31-14](https://user-images.githubusercontent.com/27635022/34535103-f9341980-f0d1-11e7-8741-41b62067a0cb.jpg)
modlist:

1. [FNEI_0.0.16](https://mods.factorio.com/mods/npo6ka/FNEI)
2. [Rampant_0.16.2](https://mods.factorio.com/mods/Veden/Rampant)
3. [rso-mod_3.5.1](https://mods.factorio.com/mods/orzelek/rso-mod)
4. [Swarm_1.2.0](https://mods.factorio.com/mods/Supercheese/Swarm)
5. [xander-mod_1.4.1](https://mods.factorio.com/mods/Repofme1/xander-mod)

**Comment by Repofme1** [comment]
Should be fixed (again) with commit [https://github.com/Factorio-Xander-Mod/Xander-Mod/commit/325a6b85273726c6c01669823d49b49a3533cd6f](url)

I didn't find a problem with burner inserters, either interacting or blueprinting.
