### ISSUE TITLE
Invalid recipe category in recipe "crystal-diamond"

### ISSUE THREAD

**Issue by wheybags** [Factorio-Xander-Mod/Xander-Mod#25]
Hey, just letting you know that you've got an invalid recipe category (empty string).
In 0.16.23, this will error on mod loading, but atm it can cause crashes: https://forums.factorio.com/57443

**Comment by Repofme1** [comment]
Thanks for the notice, sorry I didn't see it here until now.  We caught it on the forums too, was fixed in XM 1.5.1.
