### ISSUE TITLE
Refractory Brick 1 tech unlocks wrong recipe

### ISSUE THREAD

**Issue by VoidPhantom** [Factorio-Xander-Mod/Xander-Mod#26]
Refractory Brick 1 (`brick-clay`) technology unlocks only the `brick-clay-a` recipe, which is already unlocked at the beginning of the game. At the same time, there is a recipe called `brick-clay-b`, which does not seem to be unlocked by anything. Perhaps the `brick-clay` tech was meant to unlock `brick-clay-b` instead?

**Comment by Repofme1** [comment]
Should be fixed on my local copy, will be in next commit and release (not sure when those will be, commit hopefully soon but release will take longer).
