### ISSUE TITLE
Recipes for Heavy Mineral Sands are not tied to researches.

### ISSUE THREAD

**Issue by ironchefpython** [Factorio-Xander-Mod/Xander-Mod#3]
"chromite-flotation", "rutile-flotation", and "zirconia-flotation" are not unlocked by any researches.

As a simple fix, they can either all be dumped in Surfactant Mineral Flotation, or tied to Chromium Refining, Titanium Refining, and Zirconium Refining, respectively.

**Comment by Repofme1** [comment]
I added the unlocks for these three to their respective technologies, just have to push the new branch.
